title: Clarity Show Cases
tagline: "Mooie voorbeelden van hoe #publictech in de praktijk wordt ingezet" 

collections:
  cbases:
    output: true
    permalink: /cbase/:slug/
  showcases:
    output: true
    permalink: /showcase/:slug/
