title: Clarity Show Cases
description: "Mooie voorbeelden van hoe #publictech in de praktijk wordt ingezet" 

collections:
  cbases:
    output: true
    permalink: /cbase/:slug/
  showcases:
    output: true
    permalink: /showcase/:slug/
  api:
    output: true
    permalink: /cbase/:slug.json

defaults:
  -
    scope:
      path: "_api"
    values:
      layout: "cbase.json"